//DO NOT EDIT THIS FILE -- YOU CAN CREATE A `credentials.js` WHICH IS GITIGNORED IF YOU DO NOT WANT TO USE ENV VARS

module.exports = {
    host     : '139.99.7.67',
    user     : 'root',
    password : '',
    database : 'judgepad'
}
